import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('profile enhancements', () => {
  it('keeps enhancements separate from subscription content', () => {
    const profiles = readFileSync(resolve(__dirname, '../pages/ProfilesPage.vue'), 'utf8')
    const editor = readFileSync(resolve(__dirname, '../components/ProfileExtensionEditor.vue'), 'utf8')
    const styles = readFileSync(resolve(__dirname, '../styles.css'), 'utf8')
    for (const label of ['编辑规则', '编辑节点', '编辑代理组', '扩展覆写配置', '扩展脚本']) expect(profiles).toContain(label)
    expect(editor).toContain('/extensions/${props.kind}')
    expect(editor).not.toContain('点击“应用”后生效')
    expect(editor).toContain("jsonRequest('PUT', { content: content.value, apply: true })")
    expect(editor).toContain("streamProfileJob(result.jobId")
    expect(editor).toContain("'保存并应用中…') : '保存并应用'")
    expect(editor).toContain('已保存并应用，配置已立即生效')
    expect(editor).not.toContain('校验并保存')
    expect(editor).toContain("{ method: 'DELETE' }")
    expect(profiles).toContain('全局扩展覆写配置')
    expect(profiles).toContain('全局扩展脚本')
    expect(profiles).toContain('aria-label="编辑全局扩展覆写配置"')
    expect(profiles).toContain('aria-label="编辑全局扩展脚本"')
    expect(profiles).toContain('const showStructuredExtensionEditors = false')
    expect(profiles).toContain('<template v-if="showStructuredExtensionEditors">')
    expect(styles).toContain('.profile-edit-popover .profile-edit-secondary')
    expect(styles).toContain('border-radius:0 0 7px 7px;color:var(--text)')
    expect(editor).toContain('/api/profiles/global/extensions/${props.kind}')
    expect(editor).not.toContain('定义 main(config, profileName)')
    expect(editor).not.toContain('已启用全局增强')
    expect(editor).not.toContain('JavaScript')
    expect(editor).not.toContain('profile-extension-head')
    expect(styles).toContain('height:min(760px,calc(100vh - 40px))')
    expect(styles).toContain('textarea.profile-extension-editor{min-height:0;max-height:none;flex:1;resize:none}')
    expect(profiles).toContain("window.addEventListener('pointerdown', handlePagePointerDown)")
    expect(profiles).toContain("window.removeEventListener('pointerdown', handlePagePointerDown)")
    expect(profiles).toContain("if (event.key === 'Escape') closeEditMenu()")
    expect(profiles).not.toContain('<details class="profile-edit-menu">')
  })
})
